import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <footer className="py-3 text-center text-[10px] text-slate-300">
          Designed &amp; developed by{" "}
          <a href="https://www.vadigitalservices.com" target="_blank" rel="noopener noreferrer"
            className="hover:text-slate-500 transition-colors">
            VA Digital Services
          </a>
        </footer>
      </body>
    </html>
  );
}
